import ProductCard, { product } from '@/components/ProductCard';
import useProducts from '@/hooks/useProducts'
import Head from 'next/head'

export default function Home() {
  const { data: products, isLoading, isError } = useProducts();
  console.log(products)

  if (isLoading) {
    return <div>Loading...</div>
  }
  if (isError) {
    return <div>Sorry something went wrong!!</div>
  }

  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-screen h-screen mt-20'>
        <div className='px-5 md:grid grid-cols-3 gap-2'>
          {products.map((product: product) => <ProductCard product={product} />)}
        </div>
      </main>
    </>
  )
}
